### ISSUE TITLE
Flask (server)

### ISSUE THREAD

**Issue by alanctkc** [smallstep/hello-mtls#11]

**Comment by alanctkc** [comment]
@sourishkrout I just worked to pick this one up, and it looks like it is possible to terminate TLS and do client auth on the flask layer using `pyopenssl`, but it's definitely not recommended.

Should we write docs for tech like this at all? If we do, should we write them and recommend using nginx or apache for TLS?

I'm inclined to just exclude them from the list so people don't get confused. Closing for now with that approach, but I'll reopen if we think we should document not-recommended approaches, or try to document for a bunch of other servers/reverse proxies.

**Comment by sourishkrout** [comment]
@alanctkc agreed. flask sounds like a case were people would be better off using a ingress/egress proxy such as linkerd or envoy.
