### ISSUE TITLE
PHP (server and client)

### ISSUE THREAD

**Issue by alanctkc** [smallstep/hello-mtls#21]
This could be split into multiples. Not sure what popular options are... Laravel, Symfony, ??? Or maybe TLS just terminates at the Apache/nginx web server for PHP, not sure whether they encourage running your own pure PHP server and reverse proxying these days.

**Comment by alanctkc** [comment]
@sourishkrout Here's another example where PHP doesn't seem to offer native support, but most recommendations point to Nginx or Apache.

**Comment by sourishkrout** [comment]
I've asked my friend who's a PHP guy to help shed light on this...

**Comment by alanctkc** [comment]
When I left PHP world, they used fastcgi with Apache or Nginx to run it usually. I'm not sure if they've moved to the model of so many other languages, where they bind a port themselves, then optionally use a reverse proxy. If so, TLS termination might make sense on that layer.

From a quick glance around the web, it seems like it's still fastcgi, and they now have a standalone server but only recommend it in development.

**Comment by alanctkc** [comment]
Regardless, we should write PHP client docs!
